# Generated by Django 5.0 on 2024-01-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='product_id',
        ),
    ]
