services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A mysite worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis